### ISSUE TITLE
佬有没有意向做成定时触发

### ISSUE THREAD

**Issue by SkinnyLi** [MuXia-0326/YunzaiBotJsPluginMuXia#1]
比如每天七八点推送，挺舒服

**Comment by MuXia-0326** [comment]
国庆节过后看看吧，这个公众号不一定定时推文，所以得看看

**Comment by Shmily40** [comment]
Linux下的ffmpeg编译amr可以帮忙不 有偿 可以的话加v ：shmilykoi

**Comment by MuXia-0326** [comment]
定时触发添加好了，代码更新上去了，至于定时的时间，根据自己的需求调整
