### ISSUE TITLE
之前的60s日报api有更新了

### ISSUE THREAD

**Issue by Satori3rdEye** [MuXia-0326/YunzaiBotJsPluginMuXia#3]
http://bjb.yunwj.top/php/api/html.html
现在这个字体看着实在是有点难受

**Comment by MuXia-0326** [comment]
你发的这个网址好像没法访问

**Comment by Satori3rdEye** [comment]
> 你发的这个网址好像没法访问

api的话是这个http://bjb.yunwj.top/php/60miao/qq.php

**Comment by MuXia-0326** [comment]
为什么你发的两个网址我都打不开？

**Comment by MuXia-0326** [comment]
行吧，我知道了，过两天改一下

**Comment by MuXia-0326** [comment]
https://github.com/MuXia-0326/YunzaiBotJsPluginMuXia/commit/d117412c95639899a46a59e77cfa5bde38a48172
修改好了
