### ISSUE TITLE
推荐60s日报功能更换一下API

### ISSUE THREAD

**Issue by MuNitCat** [MuXia-0326/YunzaiBotJsPluginMuXia#4]
现在这个API偶尔抽风，要么没图片，要么新闻信息有点乱来
只需要改两个地方，注释的地方是原来的
```js
// let url = `http://bjb.yunwj.top/php/tp/lj.php`;
 let url = `https://api.03c3.cn/zb/api.php`;
................
// let msg = [segment.image(res.tp1)];
let msg = [segment.image(res.imageUrl)];
```

**Comment by MuXia-0326** [comment]
没图片的问题可能是你没更新最新的代码，最新的代码解决了这个问题
至于你说的新闻信息乱来，展开说一说，举了栗子啥的

**Comment by MuNitCat** [comment]
比如下面这张 6和10  来源于2023.02.26日的，
当时用的应该还是这个http://bjb.yunwj.top/php/tp/lj.php 获取的新闻内容比较模糊且比较无意义，这样的次数还挺多的
因为看更新日志的内容没再次提及日报的更新，以为到10.14就是最新的了，11月份的时候我更新过一次

> 2022-10-14 新增60s 读懂世界插件，上传部分重构插件

![I5(X8N) Y8Q69HQ@`_A}4R7](https://user-images.githubusercontent.com/56761979/221754284-1bd732de-9139-4f68-82f2-1f64a7bdad02.gif)
